# NFL Pickem Helper  

Trying to use stats sights to help with pickem ....

https://www.pro-football-reference.com/years/2019

In [1]:
import io
import os
import requests
import pandas as pd
import numpy as np

from collections import Counter

In [2]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

## Odds    
Not using .... because as games end, they disappear

In [3]:
#odds_page = 'http://www.footballlocks.com/nfl_odds.shtml'

In [4]:
# response = requests.get(odds_page)
# html = response.content
# df_list = pd.read_html(html)
# df_odds = df_list[35]

## Picks    
Using ESPN, site seems clean to extract from ....

In [5]:
picks_page = 'http://www.espn.com/nfl/picks'

In [6]:
response = requests.get(picks_page)
html = response.content
df_list = pd.read_html(html)
df_picks = df_list[0]

#### Finding table in HTML, data  - BELOW JUST TEMP

In [7]:
#import pyperclip
# #pyperclip.copy('The text to be copied to the clipboard.')
# #pyperclip.paste()

#pyperclip.copy(response.text)

In [8]:
#len(df_list)
# for i in range(len(df_list)):
#     print("List",i)
#     print(df_list[i].head(2))

#### ABOVE JUST TEMP

In [9]:
# Columns based on Analyst name and a fix
all_cols = df_picks.iloc[1]
all_cols[0] = 'GameInfo'

In [10]:
df_picks.columns = all_cols
df_picks

1                     GameInfo                       Bowen                        Clay                       Golic                    Graziano                       Kimes                        Reid                     Riddick                     Seifert                  Wickersham                       Wingo                    Pick 'em                         NaN                         NaN                         NaN
0   NFL Expert Picks - Week 10  NFL Expert Picks - Week 10  NFL Expert Picks - Week 10  NFL Expert Picks - Week 10  NFL Expert Picks - Week 10  NFL Expert Picks - Week 10  NFL Expert Picks - Week 10  NFL Expert Picks - Week 10  NFL Expert Picks - Week 10  NFL Expert Picks - Week 10  NFL Expert Picks - Week 10  NFL Expert Picks - Week 10  NFL Expert Picks - Week 10  NFL Expert Picks - Week 10  NFL Expert Picks - Week 10
1                     GameInfo                       Bowen                        Clay                       Golic                    Graziano                       Kimes                        Reid                     Riddick                     Seifert                  Wickersham                       Wingo                    Pick 'em                         NaN                         NaN                         NaN
2                          NaN                         NaN                         NaN                         NaN                         NaN                         NaN                         NaN                         NaN                         NaN                         NaN                         NaN                         NaN                         NaN                         NaN                         NaN
3          LAC @ OAKThu 8:20PM                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                         NaN                         NaN                         NaN
4          DET @ CHISun 1:00PM                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                         NaN                         NaN                         NaN
5          BAL @ CINSun 1:00PM                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                         NaN                         NaN                         NaN
6          BUF @ CLESun 1:00PM                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                         NaN                         NaN                         NaN
7           ATL @ NOSun 1:00PM                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                         NaN                         NaN                         NaN
8          NYG @ NYJSun 1:00PM                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                         NaN                         NaN                         NaN
9           ARI @ TBSun 1:00PM                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                         NaN                         NaN                         NaN
10          KC @ TENSun 1:00PM                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                         NaN                         NaN                         NaN
11         MIA @ INDSun 4:05PM                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                         NaN                         NaN                         NaN
12          CAR @ GBSun 4:25PM                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                         NaN                         NaN                         NaN
13         LAR @ PITSun 4:25PM                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                         NaN                         NaN                         NaN
14         MIN @ DALSun 8:20PM                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                         NaN                         NaN                         NaN
15          SEA @ SFMon 8:15PM                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                    No pick.                         NaN                         NaN                         NaN
16                   Last Week                    Bowen7-7                     Clay9-5                    Golic8-6                 Graziano9-5                    Kimes8-6                     Reid7-7                  Riddick7-7                 Seifert10-4              Wickersham10-4                   Wingo11-3                 Pick 'em8-6                         NaN                         NaN                         NaN
17              Through Week 9                  Bowen91-43                   Clay79-55                  Golic82-52               Graziano82-52                  Kimes83-51                   Reid80-54                Riddick83-51                Seifert89-45             Wickersham86-48                  Wingo91-43               Pick 'em88-46                         NaN                         NaN                         NaN

In [11]:
# just the named lick cols
df_picks_cols = df_picks.columns
df_picks_cols = df_picks_cols[1:-3]
df_picks_cols

Index(['Bowen', 'Clay', 'Golic', 'Graziano', 'Kimes', 'Reid', 'Riddick', 'Seifert', 'Wickersham', 'Wingo', 'Pick 'em'], dtype='object', name=1)

In [12]:
#df_picks[0].str.contains("@")
df_picks_games = df_picks[df_picks['GameInfo'].str.contains("@", na=False)].copy()

In [13]:
#df_picks_games.reset_index(drop = True)
df_picks_games.index = np.arange(1, len(df_picks_games) + 1)
df_picks_games

1              GameInfo     Bowen      Clay     Golic  Graziano     Kimes      Reid   Riddick   Seifert Wickersham     Wingo  Pick 'em  NaN  NaN  NaN
1   LAC @ OAKThu 8:20PM  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.   No pick.  No pick.  No pick.  NaN  NaN  NaN
2   DET @ CHISun 1:00PM  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.   No pick.  No pick.  No pick.  NaN  NaN  NaN
3   BAL @ CINSun 1:00PM  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.   No pick.  No pick.  No pick.  NaN  NaN  NaN
4   BUF @ CLESun 1:00PM  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.   No pick.  No pick.  No pick.  NaN  NaN  NaN
5    ATL @ NOSun 1:00PM  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.   No pick.  No pick.  No pick.  NaN  NaN  NaN
6   NYG @ NYJSun 1:00PM  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.   No pick.  No pick.  No pick.  NaN  NaN  NaN
7    ARI @ TBSun 1:00PM  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.   No pick.  No pick.  No pick.  NaN  NaN  NaN
8    KC @ TENSun 1:00PM  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.   No pick.  No pick.  No pick.  NaN  NaN  NaN
9   MIA @ INDSun 4:05PM  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.   No pick.  No pick.  No pick.  NaN  NaN  NaN
10   CAR @ GBSun 4:25PM  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.   No pick.  No pick.  No pick.  NaN  NaN  NaN
11  LAR @ PITSun 4:25PM  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.   No pick.  No pick.  No pick.  NaN  NaN  NaN
12  MIN @ DALSun 8:20PM  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.   No pick.  No pick.  No pick.  NaN  NaN  NaN
13   SEA @ SFMon 8:15PM  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.   No pick.  No pick.  No pick.  NaN  NaN  NaN

In [14]:
#reOrganize
df_picks_games.index.name = 'Game'
df_banana = df_picks_games.rename_axis(None, axis="columns")

In [15]:
df_banana

                 GameInfo     Bowen      Clay     Golic  Graziano     Kimes      Reid   Riddick   Seifert Wickersham     Wingo  Pick 'em  NaN  NaN  NaN
Game
1     LAC @ OAKThu 8:20PM  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.   No pick.  No pick.  No pick.  NaN  NaN  NaN
2     DET @ CHISun 1:00PM  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.   No pick.  No pick.  No pick.  NaN  NaN  NaN
3     BAL @ CINSun 1:00PM  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.   No pick.  No pick.  No pick.  NaN  NaN  NaN
4     BUF @ CLESun 1:00PM  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.   No pick.  No pick.  No pick.  NaN  NaN  NaN
5      ATL @ NOSun 1:00PM  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.   No pick.  No pick.  No pick.  NaN  NaN  NaN
6     NYG @ NYJSun 1:00PM  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.   No pick.  No pick.  No pick.  NaN  NaN  NaN
7      ARI @ TBSun 1:00PM  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.   No pick.  No pick.  No pick.  NaN  NaN  NaN
8      KC @ TENSun 1:00PM  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.   No pick.  No pick.  No pick.  NaN  NaN  NaN
9     MIA @ INDSun 4:05PM  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.   No pick.  No pick.  No pick.  NaN  NaN  NaN
10     CAR @ GBSun 4:25PM  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.   No pick.  No pick.  No pick.  NaN  NaN  NaN
11    LAR @ PITSun 4:25PM  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.   No pick.  No pick.  No pick.  NaN  NaN  NaN
12    MIN @ DALSun 8:20PM  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.   No pick.  No pick.  No pick.  NaN  NaN  NaN
13     SEA @ SFMon 8:15PM  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.  No pick.   No pick.  No pick.  No pick.  NaN  NaN  NaN

In [16]:
def summarize_predictions (row):
    row_sum = Counter(row)
    return row_sum

In [17]:
df_banana['Predictions'] = df_banana[df_picks_cols].apply(summarize_predictions,axis=1)

In [18]:
#note, the object column is still a counter
type(df_banana.iloc[2]['Predictions'])

collections.Counter

In [19]:
def most_picked(prediction_counter):
    fav = prediction_counter.most_common(1)
    #print(prediction_counter)
    #print(fav)
    #print(type(fav[0]))
    #print(fav[0][0])
    f = fav[0][0]
    
    return f

df_banana['Favorite'] = df_banana['Predictions'].apply(most_picked)

In [20]:
df_apple = df_banana[['GameInfo','Favorite','Predictions']].copy()

In [21]:
df_apple

                 GameInfo  Favorite       Predictions
Game
1     LAC @ OAKThu 8:20PM  No pick.  {'No pick.': 11}
2     DET @ CHISun 1:00PM  No pick.  {'No pick.': 11}
3     BAL @ CINSun 1:00PM  No pick.  {'No pick.': 11}
4     BUF @ CLESun 1:00PM  No pick.  {'No pick.': 11}
5      ATL @ NOSun 1:00PM  No pick.  {'No pick.': 11}
6     NYG @ NYJSun 1:00PM  No pick.  {'No pick.': 11}
7      ARI @ TBSun 1:00PM  No pick.  {'No pick.': 11}
8      KC @ TENSun 1:00PM  No pick.  {'No pick.': 11}
9     MIA @ INDSun 4:05PM  No pick.  {'No pick.': 11}
10     CAR @ GBSun 4:25PM  No pick.  {'No pick.': 11}
11    LAR @ PITSun 4:25PM  No pick.  {'No pick.': 11}
12    MIN @ DALSun 8:20PM  No pick.  {'No pick.': 11}
13     SEA @ SFMon 8:15PM  No pick.  {'No pick.': 11}

In [22]:
def parse_gameinfo(gameinfo_string):
    # split and then use ~deliminator
    pieces = gameinfo_string.split()
    vis = pieces[0]
    home =pieces[2][:-3]
    day = pieces[2][-3:]
    time = pieces[3]    
    combined = vis + '-' + home + '-' + day + '-' + time
    return combined

In [23]:
df_apple['parsed'] = df_apple['GameInfo'].apply(parse_gameinfo)

In [24]:
df_apple[['Visitor','Home','Day','Time']] = df_apple.parsed.str.split("-",expand=True,)

In [25]:
df_apple

                 GameInfo  Favorite       Predictions              parsed Visitor Home  Day    Time
Game
1     LAC @ OAKThu 8:20PM  No pick.  {'No pick.': 11}  LAC-OAK-Thu-8:20PM     LAC  OAK  Thu  8:20PM
2     DET @ CHISun 1:00PM  No pick.  {'No pick.': 11}  DET-CHI-Sun-1:00PM     DET  CHI  Sun  1:00PM
3     BAL @ CINSun 1:00PM  No pick.  {'No pick.': 11}  BAL-CIN-Sun-1:00PM     BAL  CIN  Sun  1:00PM
4     BUF @ CLESun 1:00PM  No pick.  {'No pick.': 11}  BUF-CLE-Sun-1:00PM     BUF  CLE  Sun  1:00PM
5      ATL @ NOSun 1:00PM  No pick.  {'No pick.': 11}   ATL-NO-Sun-1:00PM     ATL   NO  Sun  1:00PM
6     NYG @ NYJSun 1:00PM  No pick.  {'No pick.': 11}  NYG-NYJ-Sun-1:00PM     NYG  NYJ  Sun  1:00PM
7      ARI @ TBSun 1:00PM  No pick.  {'No pick.': 11}   ARI-TB-Sun-1:00PM     ARI   TB  Sun  1:00PM
8      KC @ TENSun 1:00PM  No pick.  {'No pick.': 11}   KC-TEN-Sun-1:00PM      KC  TEN  Sun  1:00PM
9     MIA @ INDSun 4:05PM  No pick.  {'No pick.': 11}  MIA-IND-Sun-4:05PM     MIA  IND  Sun  4:05PM
10     CAR @ GBSun 4:25PM  No pick.  {'No pick.': 11}   CAR-GB-Sun-4:25PM     CAR   GB  Sun  4:25PM
11    LAR @ PITSun 4:25PM  No pick.  {'No pick.': 11}  LAR-PIT-Sun-4:25PM     LAR  PIT  Sun  4:25PM
12    MIN @ DALSun 8:20PM  No pick.  {'No pick.': 11}  MIN-DAL-Sun-8:20PM     MIN  DAL  Sun  8:20PM
13     SEA @ SFMon 8:15PM  No pick.  {'No pick.': 11}   SEA-SF-Mon-8:15PM     SEA   SF  Mon  8:15PM

In [26]:
df_apple.to_csv('picks.csv')

## OFFENCE

In [27]:
# Got this link "using the SHARE link located just above the stat tables on the site"
table_offence = 'http://pfref.com/pi/share/PlbDq'

In [28]:
html = requests.get(table_offence).content
df_list = pd.read_html(html)
df_offence = df_list[0]

In [29]:
df_offence.columns

MultiIndex([( 'Unnamed: 0_level_0',    'Rk'),
            ( 'Unnamed: 1_level_0',    'Tm'),
            ( 'Unnamed: 2_level_0',     'G'),
            ( 'Unnamed: 3_level_0',    'PF'),
            ( 'Unnamed: 4_level_0',   'Yds'),
            (       'Tot Yds & TO',   'Ply'),
            (       'Tot Yds & TO',   'Y/P'),
            (       'Tot Yds & TO',    'TO'),
            ( 'Unnamed: 8_level_0',    'FL'),
            ( 'Unnamed: 9_level_0',  '1stD'),
            (            'Passing',   'Cmp'),
            (            'Passing',   'Att'),
            (            'Passing',   'Yds'),
            (            'Passing',    'TD'),
            (            'Passing',   'Int'),
            (            'Passing',  'NY/A'),
            (            'Passing',  '1stD'),
            (            'Rushing',   'Att'),
            (            'Rushing',   'Yds'),
            (            'Rushing',    'TD'),
            (            'Rushing',   'Y/A'),
            (            'Rushing',  '1stD'),
            (          'Penalties',   'Pen'),
            (          'Penalties',   'Yds'),
            (          'Penalties', '1stPy'),
            ('Unnamed: 25_level_0',   'Sc%'),
            ('Unnamed: 26_level_0',   'TO%'),
            ('Unnamed: 27_level_0',   'EXP')],
           )

In [30]:
df_offence

   Unnamed: 0_level_0    Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0 Unnamed: 4_level_0  Tot Yds & TO                             Unnamed: 8_level_0 Unnamed: 9_level_0  Passing                                                        Rushing                                      Penalties                       Unnamed: 25_level_0 Unnamed: 26_level_0 Unnamed: 27_level_0
                   Rk                    Tm                  G                 PF                Yds           Ply           Y/P            TO                 FL               1stD      Cmp      Att      Yds       TD      Int     NY/A     1stD      Att      Yds       TD      Y/A     1stD        Pen        Yds      1stPy                 Sc%                 TO%                 EXP
0                   1  New England Patriots                  7                223               2641           498           5.3             8                  3                155      183      278     1958       11        5      6.8       95      209      683       12      3.3       48         45        404         12                37.5                 8.0               30.17
1                   2      Baltimore Ravens                  7                214               3044           496           6.1             7                  2                172      142      221     1615       12        5      6.8       83      258     1429       10      5.5       80         53        425          9                52.1                 9.6               96.04
2                   3     Minnesota Vikings                  8                211               3172           493           6.4            10                  7                173      155      215     1891       13        3      8.2       83      263     1281       12      4.9       65         61        590         25                43.5                11.8               92.61
3                   4    Kansas City Chiefs                  7                202               2803           420           6.7             7                  6                156      167      261     2227       16        1      8.2       91      150      576        5      3.8       41         54        501         24                47.9                 8.2               92.85
4                   5        Dallas Cowboys                  7                190               3065           457           6.7             9                  2                172      168      238     2043       12        7      8.2       96      209     1022       11      4.9       60         54        535         16                44.6                12.2              111.74
5                   6      Los Angeles Rams                  7                190               2606           469           5.6            12                  5                155      176      284     1926        9        7      6.5       98      173      680       10      3.9       45         52        391         12                42.0                14.8               14.05
6                   7        Houston Texans                  7                185               2772           450           6.2            10                  4                164      163      236     1833       13        6      7.1       96      193      939        9      4.9       55         57        475         13                41.9                12.2               84.38
7                   8     Green Bay Packers                  7                184               2614           441           5.9             7                  5                148      162      250     1919       13        2      7.3       86      179      695        9      3.9       39         46        355         23                39.5                 7.4               53.98
8                   9      Seattle Seahawks                  7                181               2741           465           5.9             8                  7                158      157      230     1852       15        1      7.5       88      218      889        7      4.1       52         49        394         18                36.6                 9.8               42.05
9                  10  Tampa Bay Buccaneers                  6                173               2206           400           5.5            13                  3                130      132      220     1617       12       10      6.6       88      155      589        6      3.8       30         49        382         12                38.2                15.8                7.79
10                 11   Philadelphia Eagles                  7                171               2379           453           5.3            13                  8                138      150      246     1597       13        5      6.2       80      194      782        6      4.0       43         47        403         15                34.6                14.1               21.67
11                 12     Carolina Panthers                  6                166               2118           385           5.5             9                  8                120      130      212     1341        7        1      5.9       80      157      777       10      4.9       29         31        266         11                39.0                10.4                9.69
12                 13    New Orleans Saints                  7                164               2492           440           5.7             5                  1                140      169      245     1715       11        4      6.7       89      183      777        4      4.2       42         51        395          9                41.1                 5.5               43.25
13                 14     Arizona Cardinals                  7                161               2506           466           5.4             4                  0                145      167      259     1614        7        4      5.7       86      184      892        8      4.8       46         59        439         13                41.8                 5.1               49.66
14                 15   San Francisco 49ers                  6                156               2323           410           5.7            11                  5                131      115      168     1287        7        6      7.3       68      234     1036        8      4.4       53         35        317         10                39.1                15.9               24.96
15                 16         Detroit Lions                  6                149               2282           393           5.8             7                  4                126      136      218     1663       13        3      7.2       88      163      619        2      3.8       28         50        356         10                40.6                 8.7               36.56
16                 17       Atlanta Falcons                  7                145               2572           441           5.8            12                  4                162      208      291     2093       16        8      6.8      111      131      479        2      3.7       32         62        497         19                34.7                15.3               47.61
17                 18  Jacksonville Jaguars                  7                144               2649           444           6.0             7                  5                132      144      234     1668       11        2      6.7       80      194      981        1      5.1       41         57        504         11                37.0                 8.6                8.28
18                 19    Indianapolis Colts                  6                143               2103           399           5.3             6                  3                142      134      207     1331       14        3      6.2       71      185      772        3      4.2       47         33        244         24                40.3                 9.7               61.68
19                 20  Los Angeles Chargers                  7                140               2574           438           5.9            12                  6                158      184      277     2054       11        6      7.1      111      148      520        3      3.5       28         45        394         19                38.8                16.4               37.34
20                NaN                   NaN                NaN                NaN                NaN  Tot Yds & TO  Tot Yds & TO  Tot Yds & TO                NaN                NaN  Passing  Passing  Passing  Passing  Passing  Passing  Passing  Rushing  Rushing  Rushing  Rushing  Rushing  Penalties  Penalties  Penalties                 NaN                 NaN                 NaN
21                 Rk                    Tm                  G                 PF                Yds           Ply           Y/P            TO                 FL               1stD      Cmp      Att      Yds       TD      Int     NY/A     1stD      Att      Yds       TD      Y/A     1stD        Pen        Yds      1stPy                 Sc%                 TO%                 EXP
22                 21       New York Giants                  7                132               2300           435           5.3            18                  9                136      163      264     1561        8        9      5.5       82      151      739        6      4.9       40         42        374         14                23.4                23.4              -22.79
23                 22       Oakland Raiders                  6                127               2225           369           6.0             8                  4                122      142      192     1398        9        4      7.0       74      169      827        6      4.9       44         48        444          4                33.3                13.3               39.58
24                 23   Pittsburgh Steelers                  6                123               1659           326           5.1             8                  3                 99      124      190     1200        8        5      6.2       54      131      459        4      3.5       28         38        332         17                34.3                11.9               -7.89
25                 24         Buffalo Bills                  6                121               2167           388           5.6            11                  3                130      127      205     1352        7        8      6.1       71      167      815        6      4.9       43         51        412         16                27.8                15.3               -1.60
26                 25      Tennessee Titans                  7                121               2146           425           5.0             5                  1                130      131      205     1432        9        4      6.1       72      189      714        5      3.8       38         46        461         20                23.8                 5.0               -5.25
27                 26      Cleveland Browns                  6                120               2107           353           6.0            14                  3                105      113      201     1388        5       11      6.4       64      136      719        9      5.3       29         57        506         12                30.1                17.8              -18.11
28                 27    Cincinnati Bengals                  7                114               2137           438           4.9            15                  7                129      172      286     1765        8        8      5.7       88      128      372        3      2.9       23         47        361         18                27.3                18.2              -30.86
29                 28        Denver Broncos                  7                112               2222           438           5.1             9                  4                125      151      230     1455        6        5      5.7       78      184      767        5      4.2       35         48        406         12                29.1                11.4              -13.98
30                 29         Chicago Bears                  6                112               1582           360           4.4             6                  2                103      147      220     1162        8        4      4.9       71      125      420        2      3.4       17         46        366         15                29.2                 9.2              -23.24
31                 30   Washington Redskins                  8                 99               2089           422           5.0            14                  5                115      156      237     1411        9        9      5.4       79      163      678        2      4.2       26         62        480         10                22.4                16.5              -52.00
32                 31         New York Jets                  6                 63               1254           334           3.8            13                  5                 77      112      184      853        3        8      4.1       44      124      401        2      3.2       18         50        440         15                 9.6                16.4              -99.43
33                 32        Miami Dolphins                  6                 63               1552           358           4.3            13                  3                 98      120      214     1152        4       10      4.8       60      120      400        3      3.3       24         34        274         14                18.8                18.8              -61.02
34                NaN              Avg Team                NaN              150.0             2346.9         422.0           5.6           9.7                4.3              135.8    150.0    231.8   1605.4     10.0      5.4      6.5     81.4    174.0    741.5      6.0      4.3     39.7       48.7      410.1       14.8                35.0                12.3                 NaN
35                NaN          League Total                NaN               4799              75102         13504           5.6           311                137               4346     4800     7418    51373      320      174      6.5     2605     5567    23729      191      4.3     1269       1559      13123        472                35.0                12.3                 NaN
36                NaN              Avg Tm/G                NaN               22.4              350.9          63.1           5.6           1.5                0.6               20.3     22.4     34.7    240.1      1.5      0.8      6.5     12.2     26.0    110.9      0.9      4.3      5.9        7.3       61.3        2.2                35.0                12.3                 NaN

In [31]:
df_offence_teams = df_offence[df_offence[( 'Unnamed: 0_level_0',    'Rk')].str.match("[0-9]{1,2}", na=False)].copy()

In [32]:
#df_offence_teams.reset_index(0).reset_index(drop=True)
df_offence_teams.reset_index()
df_offence_teams.columns

MultiIndex([( 'Unnamed: 0_level_0',    'Rk'),
            ( 'Unnamed: 1_level_0',    'Tm'),
            ( 'Unnamed: 2_level_0',     'G'),
            ( 'Unnamed: 3_level_0',    'PF'),
            ( 'Unnamed: 4_level_0',   'Yds'),
            (       'Tot Yds & TO',   'Ply'),
            (       'Tot Yds & TO',   'Y/P'),
            (       'Tot Yds & TO',    'TO'),
            ( 'Unnamed: 8_level_0',    'FL'),
            ( 'Unnamed: 9_level_0',  '1stD'),
            (            'Passing',   'Cmp'),
            (            'Passing',   'Att'),
            (            'Passing',   'Yds'),
            (            'Passing',    'TD'),
            (            'Passing',   'Int'),
            (            'Passing',  'NY/A'),
            (            'Passing',  '1stD'),
            (            'Rushing',   'Att'),
            (            'Rushing',   'Yds'),
            (            'Rushing',    'TD'),
            (            'Rushing',   'Y/A'),
            (            'Rushing',  '1stD'),
            (          'Penalties',   'Pen'),
            (          'Penalties',   'Yds'),
            (          'Penalties', '1stPy'),
            ('Unnamed: 25_level_0',   'Sc%'),
            ('Unnamed: 26_level_0',   'TO%'),
            ('Unnamed: 27_level_0',   'EXP')],
           )

In [33]:
df_offence.to_csv('offence.csv')

In [34]:
df_offence_teams.columns

MultiIndex([( 'Unnamed: 0_level_0',    'Rk'),
            ( 'Unnamed: 1_level_0',    'Tm'),
            ( 'Unnamed: 2_level_0',     'G'),
            ( 'Unnamed: 3_level_0',    'PF'),
            ( 'Unnamed: 4_level_0',   'Yds'),
            (       'Tot Yds & TO',   'Ply'),
            (       'Tot Yds & TO',   'Y/P'),
            (       'Tot Yds & TO',    'TO'),
            ( 'Unnamed: 8_level_0',    'FL'),
            ( 'Unnamed: 9_level_0',  '1stD'),
            (            'Passing',   'Cmp'),
            (            'Passing',   'Att'),
            (            'Passing',   'Yds'),
            (            'Passing',    'TD'),
            (            'Passing',   'Int'),
            (            'Passing',  'NY/A'),
            (            'Passing',  '1stD'),
            (            'Rushing',   'Att'),
            (            'Rushing',   'Yds'),
            (            'Rushing',    'TD'),
            (            'Rushing',   'Y/A'),
            (            'Rushing',  '1stD'),
            (          'Penalties',   'Pen'),
            (          'Penalties',   'Yds'),
            (          'Penalties', '1stPy'),
            ('Unnamed: 25_level_0',   'Sc%'),
            ('Unnamed: 26_level_0',   'TO%'),
            ('Unnamed: 27_level_0',   'EXP')],
           )

## DEFENCE

In [35]:
# Got this link "using the SHARE link located just above the stat tables on the site"
table_defence = 'http://pfref.com/pi/share/gxmXp'

In [36]:
html = requests.get(table_defence).content
df_list = pd.read_html(html)
df_defence = df_list[0]

In [37]:
df_defence

   Unnamed: 0_level_0    Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0 Unnamed: 4_level_0  Tot Yds & TO                             Unnamed: 8_level_0 Unnamed: 9_level_0  Passing                                                        Rushing                                      Penalties                       Unnamed: 25_level_0 Unnamed: 26_level_0 Unnamed: 27_level_0
                   Rk                    Tm                  G                 PF                Yds           Ply           Y/P            TO                 FL               1stD      Cmp      Att      Yds       TD      Int     NY/A     1stD      Att      Yds       TD      Y/A     1stD        Pen        Yds      1stPy                 Sc%                 TO%                 EXP
0                   1  New England Patriots                  7                 48               1562           394           4.0            22                  4                 88      123      242     1039        1       18      3.9       50      126      523        2      4.2       22         42        391         16                 5.4                22.8              157.52
1                   2   San Francisco 49ers                  6                 64               1341           318           4.2            13                  6                 75       91      165      801        5        7      4.3       37      133      540        1      4.1       31         43        350          7                16.7                18.2               90.62
2                   3         Buffalo Bills                  6                 91               1756           371           4.7            10                  4                104      128      218     1208        4        6      5.2       61      140      548        6      3.9       32         45        334         11                17.1                14.3               29.18
3                   4         Chicago Bears                  6                105               1985           404           4.9            10                  6                129      158      229     1419        6        4      5.7       82      157      566        6      3.6       33         46        372         14                27.9                14.7                5.61
4                   5      Tennessee Titans                  7                112               2296           435           5.3             9                  3                129      162      247     1630       10        6      6.1       84      169      666        3      3.9       33         60        485         12                25.0                10.7               17.24
5                   6        Dallas Cowboys                  7                124               2274           427           5.3             9                  6                139      163      248     1596        6        3      6.0       77      162      678        7      4.2       44         50        452         18                32.9                12.3              -11.25
6                   7   Pittsburgh Steelers                  6                131               2126           408           5.2            15                  7                136      143      213     1465       10        8      6.3       79      175      661        4      3.8       43         49        445         14                36.8                22.1                3.19
7                   8     Minnesota Vikings                  8                132               2511           496           5.1            13                  5                158      198      292     1796       14        8      5.7      107      181      715        1      4.0       31         53        454         20                30.5                15.9                0.26
8                   9     Carolina Panthers                  6                133               2064           418           4.9            15                  6                128      146      239     1350        7        9      5.1       74      152      714        7      4.7       44         49        396         10                31.6                17.7               16.91
9                  10        Denver Broncos                  7                136               2118           422           5.0             6                  1                123      146      227     1367        6        5      5.7       68      182      751        5      4.1       38         51        413         17                33.3                 7.7                1.41
10                 11    Indianapolis Colts                  6                138               2167           351           6.2             7                  3                128      139      200     1501       11        4      6.9       76      135      666        4      4.9       43         56        482          9                40.7                10.2              -40.56
11                 12     Green Bay Packers                  7                139               2667           443           6.0            13                  5                141      145      240     1765        9        8      6.8       85      185      902        7      4.9       46         57        598         10                31.3                15.7              -10.90
12                 13  Los Angeles Chargers                  7                141               2333           394           5.9             8                  2                129      138      185     1513       12        6      7.6       74      195      820        5      4.2       47         47        420          8                33.3                11.6              -58.43
13                 14    New Orleans Saints                  7                147               2295           423           5.4             9                  6                129      156      251     1661       10        3      6.1       86      152      634        7      4.2       30         38        306         13                31.6                11.8              -18.81
14                 15  Jacksonville Jaguars                  7                148               2527           443           5.7             6                  2                142      149      251     1707        9        4      6.3       86      171      820        7      4.8       41         43        406         15                32.5                 6.3              -28.34
15                 16    Kansas City Chiefs                  7                150               2642           482           5.5            11                  5                170      162      253     1600        8        6      5.9       91      209     1042        9      5.0       59         53        384         20                38.7                14.7              -31.78
16                 17      Cleveland Browns                  6                154               2240           391           5.7             8                  4                129      128      189     1316       12        4      6.3       71      183      924        5      5.0       42         42        306         16                35.6                11.0              -33.47
17                 18         New York Jets                  6                156               2113           408           5.2             9                  4                125      149      231     1560        6        5      6.6       74      170      553       10      3.3       33         49        446         18                35.6                 9.6              -13.21
18                 19      Baltimore Ravens                  7                156               2448           399           6.1             9                  3                132      149      251     1858        7        6      7.1       81      136      590        8      4.3       33         44        320         18                41.7                11.1              -38.92
19                 20         Detroit Lions                  6                160               2573           420           6.1            11                  8                147      141      241     1738       10        3      6.9       88      169      835        7      4.9       37         39        294         22                41.2                13.2              -61.16
20                NaN                   NaN                NaN                NaN                NaN  Tot Yds & TO  Tot Yds & TO  Tot Yds & TO                NaN                NaN  Passing  Passing  Passing  Passing  Passing  Passing  Passing  Rushing  Rushing  Rushing  Rushing  Rushing  Penalties  Penalties  Penalties                 NaN                 NaN                 NaN
21                 Rk                    Tm                  G                 PF                Yds           Ply           Y/P            TO                 FL               1stD      Cmp      Att      Yds       TD      Int     NY/A     1stD      Att      Yds       TD      Y/A     1stD        Pen        Yds      1stPy                 Sc%                 TO%                 EXP
22                 21      Los Angeles Rams                  7                164               2305           453           5.1            12                  6                142      154      239     1634       10        6      6.4       95      196      671        7      3.4       36         51        415         11                36.6                13.4                3.03
23                 22        Houston Texans                  7                164               2519           439           5.7            10                  7                147      187      277     1929       15        3      6.6      104      145      590        3      4.1       27         53        409         16                40.0                13.3              -39.71
24                 23       Oakland Raiders                  6                165               2259           359           6.3             5                  2                124      137      203     1739       16        3      8.2       78      146      520        5      3.6       26         40        347         20                43.5                 8.1              -79.17
25                 24      Seattle Seahawks                  7                176               2499           414           6.0            12                  6                133      156      250     1743        8        6      6.7       84      153      756        9      4.9       37         53        452         12                37.8                13.5              -26.61
26                 25  Tampa Bay Buccaneers                  6                185               2235           404           5.5            11                  6                132      159      250     1827       11        5      6.9       91      141      408        6      2.9       24         44        372         17                41.9                13.5               -8.81
27                 26   Philadelphia Eagles                  7                186               2520           439           5.7            11                  3                139      167      254     1894       14        8      7.0       91      168      626        7      3.7       33         55        412         15                40.0                13.8              -32.77
28                 27    Cincinnati Bengals                  7                186               3016           472           6.4             6                  4                158      138      210     1693        9        2      7.7       78      253     1323        9      5.2       70         61        529         10                42.7                 7.3              -71.44
29                 28       New York Giants                  7                187               2719           453           6.0             8                  2                146      149      216     1799       10        6      7.7       92      219      920       10      4.2       42         56        417         12                38.8                10.0              -42.29
30                 29     Arizona Cardinals                  7                192               2747           460           6.0             6                  5                164      171      245     1843       17        1      6.9      103      193      904        3      4.7       45         50        428         16                45.2                 6.8              -74.55
31                 30   Washington Redskins                  8                195               3027           534           5.7            11                  3                175      192      264     1925       14        8      6.8       96      251     1102        6      4.4       59         49        420         20                42.0                13.6              -56.99
32                 31        Miami Dolphins                  6                211               2504           379           6.6             2                  1                140      116      168     1539       16        1      8.8       75      204      965        7      4.7       52         42        422         13                50.8                 3.1              -99.17
33                 32       Atlanta Falcons                  7                223               2714           451           6.0             4                  2                165      160      230     1918       17        2      8.2       87      216      796        8      3.7       56         49        446         22                52.9                 2.9             -116.40
34                NaN              Avg Team                NaN              150.0             2346.9         422.0           5.6           9.7                4.3              135.8    150.0    231.8   1605.4     10.0      5.4      6.5     81.4    174.0    741.5      6.0      4.3     39.7       48.7      410.1       14.8                35.0                12.3               -20.9
35                NaN          League Total                NaN               4799              75102         13504           5.6           311                137               4346     4800     7418    51373      320      174      6.5     2605     5567    23729      191      4.3     1269       1559      13123        472                35.0                12.3                 NaN
36                NaN              Avg Tm/G                NaN               22.4              350.9          63.1           5.6           1.5                0.6               20.3     22.4     34.7    240.1      1.5      0.8      6.5     12.2     26.0    110.9      0.9      4.3      5.9        7.3       61.3        2.2                35.0                12.3                 NaN

In [38]:
df_defence.to_csv('defence.csv')